### ISSUE TITLE
Chylina spawns in a wall

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#363]
**Describe Your Issue**
Chylina spawns in a wall

**Steps To Reproduce**
 NPC in wall

https://classic.wowhead.com/npc=4084

**Expected Behaviour**
NPC should not be spawned in a wall, should be behind the desk.
.die & resp spawns her back in the call
.go c Chylina take you to correct spawn point

**Comment by ratkosrb** [comment]
She is only inside a wall because of the mismatch between content patch and client patch on the server. Her coordinates are correct for the patch, here is how the area looks with the 1.6 client.

![WoWScrnShot_021921_140134](https://user-images.githubusercontent.com/35845488/108502252-321acc80-72bb-11eb-802b-3a4bd9553a0e.jpg)

Her position was updated in patch 1.11 when the layout of the area changed.
