### ISSUE TITLE
Verog the Dervish quest

### ISSUE THREAD

**Issue by darklord221** [the-hyjal-project/bugtracker#399]
**Describe Your Issue**
mob is never spawned.. even if you kill a ton of mobs which should spawn the quest mob he never spawns.. after a hour of farming kolkar he never showed up.. 
**Steps To Reproduce**

1. accept quest verog the dervish
2. gl killing a non existant mob
3. 

NPC: https://classic.wowhead.com/npc=
Item: https://classic.wowhead.com/item=
Quest: https://classic.wowhead.com/quest=851/verog-the-dervish
Spell: https://classic.wowhead.com/spell=
Object: https://classic.wowhead.com/object=

**Expected Behaviour**
https://www.youtube.com/watch?v=G9zsm89HJj4

**Comment by Simp-N** [comment]
I did this quest with a group. Sure took all a lot of kills but eventually he spawned. Unfortunetly one of the group members didnt get it because he was too far away when Verog was killed. We kept killing centaurs so he'd spawn again and it took a lot of time but eventually he did. So he can spawn but perhaps the chance for him to spawn should be increased. I dont idk

**Comment by Neto-WoW** [comment]
Updated to be consistent and handled in core.
