### ISSUE TITLE
Volcor (id 3692) is just sitting here when he should be in the cave.

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#47]
**Describe Your Issue**
Volcor (id 3692) is just sitting here when he should be in the cave. Someone might've started the quest https://classic.wowhead.com/quest=994/escape-through-force and maybe he just never despawned.

https://cdn.discordapp.com/attachments/780923795782369360/783579148689735691/WoWScrnShot_120220_081316.jpg

**Steps To Reproduce**

1.
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected Behavior**

**Comment by petage** [comment]
Adding a link to the [NPC](https://classic.wowhead.com/npc=3692/volcor) in question. This issue is definitely related to the escort quest [Escape Through Force](https://classic.wowhead.com/quest=994/escape-through-force) which has similar issues as #46. [Here](https://cdn.discordapp.com/attachments/780923795782369360/783586532044308480/2020-12-02_08-50-48.mp4) is a video related to the quest.

**Comment by ratkosrb** [comment]
Fixed in https://github.com/vmangos/core/commit/0a24e43fe353853d860b5349c3677a6d9d9867db
