### ISSUE TITLE
theres no flight master in ungoro in this patch

### ISSUE THREAD

**Issue by GM-Dave-THP** [the-hyjal-project/bugtracker#8]
**Describe Your Issue**
we have experienced a thing during gurubashi
theres no flight master in ungoro in this patch
but theres the ungoro flightmaster standing in silithus entrance
you talk to him he gets teleported to un'goro
and from now on you can fly to un'goro
but not back
same for alliance and horde flight masters

**Steps To Reproduce**

1.
2. 
3. 

Item: https://wowhead.com?item=
Quest: https://wowhead.com?quest=
Spell: https://wowhead.com?spell=

**Expected Behavior**

Needs verification

**Comment by kodolol** [comment]
Excerpt from gamemechanic:

_"upto patch 1.8 there is two flightmasters at valors rest in silithus. Horde at the north of the road - and ally to the south. These are different from the ungoru flightmaster.
There is no way to make them 100% work with 1.12 client without altering the gamefiles - because their taxinode id's have been reused for Cenarion hold.
The reason they are there is; that if you compile vmangos to be used with an older client - they would work.
from a emulation view - its as close to perfect as possible. From a players view its pure crap. Maybe hyjal team can come up with a better solution."_

**Comment by Nolin7777** [comment]
Since it's flightpoints are hardcoded in the 1.12 client we aren't able to remove some to be patch appropriate.
We are still deciding if we want to spawn all flightmasters on patch 1.2 or not.
