### ISSUE TITLE
Silly tooltips for world objects.

### ISSUE THREAD

**Issue by Simp-N** [the-hyjal-project/bugtracker#93]
**Describe Your Issue**
There are at least three objects in the world with tooltips that appear to be a bit off. 
["TEMP Ruins of Stardust Fountain"](https://classicdb.ch/?object=300148) at 33,67 in Ashenvale
["TEMP Quilboar Watering Hole"](https://classicdb.ch/?object=300146) at 44,74 in Barrens
["TEMP Spring Well"](https://classicdb.ch/?object=300147) at 62,20 in Hillsbrad Foothills

**Screenshots**
![Sorted_WoWScrnShot_201209_170221](https://user-images.githubusercontent.com/75734743/101658695-8a288d80-3a45-11eb-8677-a51bb92e585e.png)
![Sorted_WoWScrnShot_201209_171507](https://user-images.githubusercontent.com/75734743/101658726-914f9b80-3a45-11eb-8002-81f82692d326.png)
![Sorted_WoWScrnShot_201209_173157](https://user-images.githubusercontent.com/75734743/101658766-9dd3f400-3a45-11eb-8e88-29fa5e9aa009.png)

**Steps To Reproduce**
1. Go to the coords provided
2. Mouse over the objects

**Expected Behavior**
Obviously the TEMP should be removed from these tooltips.

There may be more tooltips that are weird like this. I found one called "Purple aura, short column, 0.6 scale" in the database, but without magical GM powers I couldn't figure out where it was in-game.

**Comment by GM-Dave-THP** [comment]
![image](https://user-images.githubusercontent.com/19539976/101661281-04eeaa00-3a40-11eb-99f0-d397a174e81b.png)

**Comment by GM-Dave-THP** [comment]
Confirmed

**Comment by Gamemechanicwow** [comment]
I would really like to know what names are shown in classic? There was a few odd objectnames in vanilla :>

I suspect that the names are accurate sniffs, but shouldn't be shown - since they aren't physical objects but spell focuses (type=8) and there isn't a visible model for displaymodel for id 1287(?)

For spellfocuses the data3 field indicates whether its serverOnly. Setting it to 1 would hide the object from the players and the object would still function as a spellfocus.

`UPDATE gameobject_template SET DATA3=1 WHERE entry IN (300146, 300147, 300148);`

**Comment by Simp-N** [comment]
@Gamemechanicwow 
I checked these places in Classic and none of them showed any tooltip at all. I tried desperately waving my cursor all over the screen but no tooltip showed up.

**Comment by Nolin7777** [comment]
credits to vmangos
